### ISSUE TITLE
[IMPORTANT] Cannot view reports by "Outcome Area" if report created with NO outcome areas selected

### ISSUE THREAD

**Issue by geoff-igiari** [toby-1-kenobi/sag_reporter#59] opened 2015-11-25 01:49 UTC
**environment**: lcreporter-test
**priority of issue:** Should be fixed ASAP
**issue reproducible in:** all browsers

**impact of issue:**
ALL users with privileges to view reports cannot view the report under "Outcome Area". This will continue to be reproducible until the issue (with no outcome areas selected) is identified and removed from the system (which all users do not have privileges to do). 

The following error shows:

![error](https://cloud.githubusercontent.com/assets/15933209/11386108/9024d1c8-9372-11e5-8ff6-e1b83645c71b.png)

**Steps to reproduce**
1. Create a new report with _NO_ outcome areas selected
2. Login as a user with report view privileges (e.g. Manager or Admin)
3. Click "View all reports"
4. Select to view report by "Outcome Area"
![report_view](https://cloud.githubusercontent.com/assets/15933209/11386142/e2a1a034-9372-11e5-82b2-8c5aae7354c9.png)

**Comment by toby-1-kenobi** [comment] 2015-11-25 06:11
Duplicate of issue #58

**Closed as completed by toby-1-kenobi** 2015-11-25 06:11 UTC

**Comment by geoff-igiari** [comment] 2015-11-25 06:31
Sorry about duplicate issue - I thought I had closed my tab and lost my issue that I was writing.
